object AbiMediaTypes {

    val MT_USER     = """application/vnd.abiquo.user+xml; version=2.0"""
    val MT_USERS    = """application/vnd.abiquo.users+xml; version=2.0"""
    val MT_DCS      = """application/vnd.abiquo.datacenters+xml;version=2.0"""
    val MT_DC       = """application/vnd.abiquo.datacenter+xml; version=2.0"""
    val MT_RACKS    = """application/vnd.abiquo.racks+xml; version=2.0"""
    val MT_RACK     = """application/vnd.abiquo.rack+xml; version=2.0"""
    val MT_MACHINE  = """application/vnd.abiquo.machine+xml; version=2.0"""
    val MT_MACHINES = """application/vnd.abiquo.machines+xml; version=2.0"""
    val MT_RES_ENT  = """application/vnd.abiquo.enterpriseresources+xml; version=2.0"""
    val MT_RES_VDC  = """application/vnd.abiquo.virtualdatacentersresources+xml; version=2.0"""
    val MT_RES_VAPP = """application/vnd.abiquo.virtualappsresources+xml; version=2.0"""
    val MT_CLOUDUSAGE="""application/vnd.abiquo.cloudusage+xml; version=2.0"""
    val MT_DC_REPO  = """application/vnd.abiquo.datacenterrepository+xml; version=2.0"""
    val MT_VDCS     = """application/vnd.abiquo.virtualdatacenters+xml; version=2.0"""
    val MT_VDC      = """application/vnd.abiquo.virtualdatacenter+xml; version=2.0"""
    val MT_VAPPS    = """application/vnd.abiquo.virtualappliances+xml; version=2.0"""
    val MT_VAPP     = """application/vnd.abiquo.virtualappliance+xml; version=2.0"""
    val MT_VMS_EXTENDED = """application/vnd.abiquo.virtualmachineswithnodeextended+xml; version=2.0"""
    val MT_VM_EXTENDED  = """application/vnd.abiquo.virtualmachinewithnodeextended+xml; version=2.0"""
    val MT_VM_NODE  = """application/vnd.abiquo.virtualmachinewithnode+xml; version=2.0"""
    val MT_VMTS     = """application/vnd.abiquo.virtualmachinetemplates+xml; version=2.0"""
    val MT_VMT      = """application/vnd.abiquo.virtualmachinetemplate+xml; version=2.0"""
    val MT_VM       = """application/vnd.abiquo.virtualmachine+xml; version=2.0"""
    val MT_VMS      = """application/vnd.abiquo.virtualmachines+xml; version=2.0"""
    val MT_VMSTATE  = """application/vnd.abiquo.virtualmachinestate+xml;version=2.0"""
    val MT_ACCEPTED = """application/vnd.abiquo.acceptedrequest+xml; version=2.0"""
    val MT_TASKS    = """application/vnd.abiquo.tasks+xml;version=2.0"""
    val MT_TASK     = """application/vnd.abiquo.task+xml;version=2.0"""
    val MT_VMTASK   = """application/vnd.abiquo.virtualmachinetask+xml"""
    val MT_VOLS     = """application/vnd.abiquo.iscsivolumes+xml; version=2.0"""
    val MT_VLAN     = """application/vnd.abiquo.vlan+xml; version=2.0"""      
    val MT_XML      = """application/xml"""
    val MT_PLAIN    = """text/plain"""
    }